site_name: "MMG:3320 Advanced Bioinformatics"
site_description: "test site" 
site_author: "Princess Rodriguez" 
site_url: https://prodriguez19.github.io/MMG3320-5320/

theme:
  name: material 
  features:
    - content.code.copy
    - content.code.annotate 
    - content.code.select
    - navigation.tabs
    - navigation.top
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home:
      - Introduction: index.md
      - Syllabus: pdf_materials/MMG3320-Spring-2026-Syllabus.pdf
      - Schedule: pdf_materials/MMG3320-Spring-2026-Schedule.pdf
      - Git Bash Install: ch01/gitbash-install.md
      - Frequently Asked Questions: FAQ.md
      - Quick Start: ch01/quick-start.md
  - Slides:
      - Overview: slides/index.md
  - Printouts:
      - Overview: pdf_materials/index.md
  - Lessons: 
      - Week 1:
          - Overview: ch01/index.md
          - Introducing the Shell (L1): ch01/01_week1_mmg3320.md
          - Navigating the Shell (L2): ch01/02_week1_mmg3320.md
      - Week 2:
          - Overview: ch02/index.md
          - Wild Cards & Nano (L3): ch02/03_week2_mmg3320.md
      - Week 3:
          - Overview: ch03/index.md
          - Searching and Redirection (L4): ch03/04_week3_mmg3320.md
          - Intro to Shell Scripting (L5): ch03/05_week3_mmg3320.md
  - Assignments:
      - Homework 1 (L2): assignments/week1_assignment.md
      - Homework 2 (L2): assignments/week2_assignment.md
      - Assignment Schedule: assignments/assignment_schedule.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - mkdocs-pdf
  - search
